### ISSUE TITLE
Order of operations

### ISSUE THREAD

**Issue by klocey** [QBstudents/QB2017_Beidler#2]
@Kvcross In Week1, under "Basic Features of Vectors" the instructions are to "add x and w and divide by 15". In other words, divide the sum of x & w by 15, i.e., (x + w)/15. This yields a different result than x + w/15, which adds x to the quotient of w and 15.

Be sure to pay mind to the instructions, order of mathematical operations, and use of parentheses. In the absence of parentheses, exponential and logarithmic operations will always be done before multiplication and division, which will always be done before addition and subtraction. Always ask if you're unsure. @jaytlennon @wrshoemaker @nwisnoski

**Comment by Kvcross** [comment]
Ok! Thanks for the heads up.
